name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 配置JDK17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 编译Release安装包
        run: |
          cd TapTest
          gradle assembleRelease

      - name: 导出成品APK
        uses: actions/upload-artifact@v4
        with:
          name: tap-arm64-apk
          path: TapTest/app/build/outputs/apk/release/app-release.apk
